language: csharp
sudo: false
solution: ValveResourceFormat.sln

os:
- linux
- osx

notifications:
  email: false

install:
  - nuget restore Rabscuttle.sln

script:
  - xbuild /p:Configuration=Release Rabscuttle.sln
  - mono ./packages/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./RabscuttleTests/