language: csharp
sudo: false
solution: Rabscuttle.sln

branches:
  only:
  - master

os:
- linux
- osx

notifications:
  email: false

install:
  - nuget restore Rabscuttle.sln

script:
  - xbuild /p:Configuration=Release Rabscuttle.sln
  - mono ./packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./RabscuttleTests/bin/Release/RabscuttleTests.dll